PLUGIN_NAME=		ctrld
PLUGIN_VERSION=		0.0.1
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		Per-VLAN DNS forwarding proxy with per-client NextDNS tagging
PLUGIN_MAINTAINER=	9576229+thatcoleyouknow@users.noreply.github.com

.include "../../Mk/plugins.mk"
